### ISSUE TITLE
Can't seem to get it to print GMT from PHP

### ISSUE THREAD

**Issue by scarstens** [JohnRDOrazio/jQuery-Clock-Plugin#4]
Maybe I'm doing something wrong, but to me it seems like the server timestamp doesn't work properly.

```php
<?php
//set time to 12AM
$timeNdate = date($dfs, mktime(0,0,0));
//create time object for html
echo "<input id='servertime' type='text' value='".strtotime($timeNdate)."' />";
?>

```
```html
<script src="jqClock.js"></script>

<div id="midnight-clock" style="text-align:center; width: 25%; display:inline-block; float: left;">
        <div class="clock"></div>

    <span class="clocklabel">Midnight</span>
    <script type="text/javascript">
                servertime = parseFloat( jQuery("input#servertime").val() ) * 1000;
                jQuery("#midnight-clock .clock").clock({"timestamp":servertime, "calendar":"false"});
    </script>

</div>
```

This ends up giving me 5:00 PM ... any idea why that would happen?

**Comment by Lwangaman** [comment]
It's been 4 years, but I have taken a deeper look into the server side timestamp issues, and I saw that javascript does actually compensate for timezone offsets, so I have now made the plugin compensate for that when a custom timestamp is passed in. However this means that the javascript will only compensate for it's own local timezone offset from UTC; it will not however take into account the timezone offset from the server. So it will still be necessary to compensate in the server side code for the server's timezone offset from UTC.
Now the only other problem is that this will screw up the custom timestamps that might be generated on the client side, in javascript. These should not be compensated for timezone offsets.
So the only solution I can think of that will encompass all cases is to make the plugin intelligent enough to recognize if the timestamp is a client side javascript timestamp, or a server side PHP unix timestamp. Which would mean no longer multiplying by 1000 before passing to the plugin, because that will actually let the plugin detect where the timestamp is coming from.
